version: '3.8'

services:
  # ------------------------------------------------------------
  # PostgreSQL: The Source of Truth (Users, Roles, Tokens)
  # ------------------------------------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: ticket_blitz_postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      # Persist data so you don't lose users when you restart Docker
      - pgdata:/var/lib/postgresql/data
    networks:
      - blitz_network
    healthcheck:
      # "Senior" Touch: The app waits for this to be healthy before connecting
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ------------------------------------------------------------
  # Redis: Caching & Rate Limiting
  # ------------------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: ticket_blitz_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - blitz_network
    command: redis-server --save 60 1 --loglevel warning

  # ------------------------------------------------------------
  # (Optional) PGAdmin: Visual Database Management
  # Great for debugging data without writing SQL queries manually
  # ------------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: ticket_blitz_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - blitz_network
    depends_on:
      - postgres

  # ------------------------------------------------------------
  # Observability Stack
  # ------------------------------------------------------------
  otel-collector:
    image: otel/opentelemetry-collector:0.111.0
    container_name: ticket_blitz_otel_collector
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    networks:
      - blitz_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ticket_blitz_jaeger
    restart: always
    ports:
      - "16686:16686" # Jaeger UI
      - "14268"
      - "14250"
    networks:
      - blitz_network

  prometheus:
    image: prom/prometheus:latest
    container_name: ticket_blitz_prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - blitz_network

  grafana:
    image: grafana/grafana:latest
    container_name: ticket_blitz_grafana
    restart: always
    ports:
      - "3001:3000"
    networks:
      - blitz_network

volumes:
  pgdata:
  redisdata:


networks:
  blitz_network:
    driver: bridge
